// `.open-next/worker.js` は OpenNext のビルドで生成される (gitignore 対象)。
// typecheck 時にはファイルが存在しないため、import を型解決から外す。
// 実体は wrangler の esbuild がビルド時に解決する。
// @ts-ignore - generated by `opennextjs-cloudflare build`
import openNextHandlerRaw from '../.open-next/worker.js'

export { SpotifyStatusDO } from './spotify-status-do'

const openNextHandler = openNextHandlerRaw as ExportedHandler<CloudflareEnv>

const WS_PATH = '/api/v1/spotify-status/ws'

const handler: ExportedHandler<CloudflareEnv> = {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)

    if (url.pathname === WS_PATH) {
      if (request.headers.get('upgrade') !== 'websocket') {
        return new Response('Expected WebSocket upgrade', { status: 426 })
      }
      const id = env.SPOTIFY_STATUS_DO.idFromName('global')
      const stub = env.SPOTIFY_STATUS_DO.get(id)
      const forwardUrl = new URL('/ws', url.origin)
      return stub.fetch(new Request(forwardUrl, request))
    }

    return openNextHandler.fetch!(request, env, ctx)
  },
}

export default handler
